version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=1
      - SA_PASSWORD=1VerySecurePassword!
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - 1433:1433

  deployDb:
    image: blazor:deployDb
    environment:
      - DBNAME=blazorcrud
      - DBPASS=1VerySecurePassword!
      - DBSERVER=db
    build:
      context: ./Db
    depends_on:
      - db
    restart: "no"

volumes:
  sql_data: